title: Devneios
email: rauanpires@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog
baseurl: ""
domain: "rauanbpk.github.io"
url: "https://rauanbpk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: RauanBPK
linkedin_username: rauan-pires

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: false
google_analytics: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      allow_comments: true
